// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230904173237_CreateSettings")]
    partial class CreateSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("api.Models.AppSettings", b =>
                {
                    b.Property<string>("SchoolLogoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SCHOOLLOGOURL");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SCHOOLNAME");

                    b.ToTable("APPSETTINGS");
                });
#pragma warning restore 612, 618
        }
    }
}
