# How to run: docker compose -f docker-compose.yml up -d
services:
  postgres:
    image: postgres:latest
    container_name: students-absence-db
    restart: always
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - data:/var/lib/sa_postgres/data

volumes:
  data:
    driver: local
